### ISSUE TITLE
Unable to download pretrained models

### ISSUE THREAD

**Issue by MetiCodePrivateLimited** [771979972/paddle-SAM#1]
I am unable to download pretrained models from the following link. I am accessing this URL from Pakistan:
 https://pan.baidu.com/s/1G-Ffs8-y93R0ZlD9mEU6Eg

It require baide netdisk setup which is in chinese language and I am unable to understand this language. Could you tell me an alternate way to download the pretrained models?

'pretrained_psp': 'pretrained_models/psp_ffhq_encode.pdparams',
	'stylegan_ffhq': 'pretrained_models/stylegan2-ffhq-config-f.pdparams',
	'ir_se50': 'pretrained_models/model_ir_se50.pdparams',
	'shape_predictor': 'shape_predictor_68_face_landmarks.dat',
	'age_predictor':'pretrained_models/dex_age_classifier.pdparams',
	
	'circular_face': 'pretrained_models/CurricularFace_Backbone.pdparams',
	'alexnet': 'pretrained_models/alexnet.pdparams',
	'lin_alex0.1': 'pretrained_models/lin_alex.pdparams',
	'mtcnn_pnet': 'models/mtcnn/mtcnn_paddle/src/weights/pnet.npy',
	'mtcnn_rnet': 'models/mtcnn/mtcnn_paddle/src/weights/rnet.npy',
	'mtcnn_onet': 'models/mtcnn/mtcnn_paddle/src/weights/onet.npy',
	'moco': 'pretrained_models/moco_v2_800ep_pretrain.pth.tar'

**Comment by 771979972** [comment]
Thanks for your suggestion, we would upload these pretrained models to google drive, and provide a link in README.md.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "771979972/paddle-SAM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月7日(星期二) 下午2:11
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[771979972/paddle-SAM] Unable to download pretrained models (#1)





 
I am unable to download pretrained models from the following link:
 https://pan.baidu.com/s/1G-Ffs8-y93R0ZlD9mEU6Eg
 
It require baide netdisk setup which is in chinese language and I am unable to understand this language. Could you tell me an alternate way to download the pretrained models?
 
'pretrained_psp': 'pretrained_models/psp_ffhq_encode.pdparams',
 'stylegan_ffhq': 'pretrained_models/stylegan2-ffhq-config-f.pdparams',
 'ir_se50': 'pretrained_models/model_ir_se50.pdparams',
 'shape_predictor': 'shape_predictor_68_face_landmarks.dat',
 'age_predictor':'pretrained_models/dex_age_classifier.pdparams',
 'circular_face': 'pretrained_models/CurricularFace_Backbone.pdparams', 'alexnet': 'pretrained_models/alexnet.pdparams', 'lin_alex0.1': 'pretrained_models/lin_alex.pdparams', 'mtcnn_pnet': 'models/mtcnn/mtcnn_paddle/src/weights/pnet.npy', 'mtcnn_rnet': 'models/mtcnn/mtcnn_paddle/src/weights/rnet.npy', 'mtcnn_onet': 'models/mtcnn/mtcnn_paddle/src/weights/onet.npy', 'moco': 'pretrained_models/moco_v2_800ep_pretrain.pth.tar'  
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MetiCodePrivateLimited** [comment]
That is great. I am waiting for a Google drive URL.

**Comment by 771979972** [comment]
Pretrained models have been uploaded to google drive.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "771979972/paddle-SAM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月7日(星期二) 下午5:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [771979972/paddle-SAM] Unable to download pretrained models (#1)





 
That is great. I am waiting for a Google drive URL.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MetiCodePrivateLimited** [comment]
Thanks.
